version: '2'
services: 

    # python  script: conversion of xmlfiles
    ingester:
        build:
            context: ./ingest_cbgxml
            dockerfile: Dockerfile
        environment: 
            LINKS_HOME: './ingest_cbgxml'         
        ports:
            - 8888:5000
        volumes:
            - ./:/usr/src/app

    mysql:
        image: mysql:5.7
        volumes: 
            - mysqlvol:/var/lib/mysql
        ports:
            - 3306:3306            
        environment:
            TZ: "Europe/Amsterdam"
            MYSQL_ROOT_PASSWORD: "rood"

            MYSQL_DATABASE: "links_general"
      
volumes:
  mysqlvol:                      
