version: '3'

services:
     ingest:
         image: registry.diginfra.net/tsd/links-ingester:latest
         environment:
             MYSQL_LINKS_HOSTURL: host.docker.internal
             MYSQL_LINKS_USERNAME: links
             MYSQL_LINKS_PASSWORD: mslinks
             MYSQL_REF_HOSTURL: host.docker.internal
             MYSQL_REF_USERNAME: links
             MYSQL_REF_PASSWORD: mslinks
             DBNAME_REF: links_general
             CBGXML_BSG_DIR: ./dataxml/BSG
             CBGXML_BSH_DIR: ./dataxml/BSH
             CBGXML_BSO_DIR: ./dataxml/BSO
         volumes:
             - ./current-run/:/usr/src/app/dataxml/
