version: '2'
services: 

    # python  script: conversion of xmlfiles
    # ingester:
    #     build:
    #         context: ./ingest_cbgxml
    #         dockerfile: Dockerfile.prod
    #     environment: 
    #         LINKS_HOME: './ingest_cbgxml'
    #         COLLECTION: 'BSH' # possible values BSO, BSH, BSG
    #     ports:
    #         - 8888:5000
    #     volumes:
    #         - ./ingest_cbgxml/:/usr/src/app
    #         - ./dataxml/:/usr/src/app/dataxml/        
       

    mysqldb:
        image: mysql:5.7.35
        volumes: 
            - mysqlvol:/var/lib/mysql
        ports:
            - 3306:3306            
        environment:
            TZ: "Europe/Amsterdam"
            MYSQL_ROOT_PASSWORD: "rood"
            MYSQL_DATABASE: "links_general"
            
    adminer:
        image: adminer
        ports:
            - 8080:8080            
      
volumes:
    mysqlvol:                      
