DROP TABLE IF EXISTS `person_c`;
CREATE TABLE `person_c` (
    `id_person` int(10) unsigned NOT NULL,
    `id_registration` int(10) unsigned DEFAULT NULL,
    `id_source` int(10) unsigned DEFAULT NULL,
    `registration_maintype` tinyint(3) unsigned DEFAULT NULL,
    `registration_type` varchar(50) COLLATE utf8_bin DEFAULT NULL,
    `id_person_o` int(10) unsigned DEFAULT NULL,
    `not_linksbase_p` varchar(10) COLLATE utf8_bin DEFAULT NULL,
    `title_noble` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `title_other` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `firstname` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    `firstname1` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `firstname2` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `firstname3` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `firstname4` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `alias_firstname` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `initials` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `patronym` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `prefix` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `familyname` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    `alias_familyname` varchar(50) COLLATE utf8_bin DEFAULT NULL,
    `suffix` varchar(15) COLLATE utf8_bin DEFAULT NULL,
    `sex` char(1) COLLATE utf8_bin DEFAULT NULL,
    `religion` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    `foundling` char(1) COLLATE utf8_bin DEFAULT NULL,
    `civil_status` varchar(30) COLLATE utf8_bin DEFAULT NULL,
    `status_mother` varchar(50) COLLATE utf8_bin DEFAULT NULL,
    `role` tinyint(3) unsigned DEFAULT NULL,
    `occupation` varchar(200) COLLATE utf8_bin DEFAULT NULL,
    `living_location` int(10) unsigned DEFAULT NULL,
    `age_literal` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    `age_day` smallint(6) DEFAULT NULL,
    `age_week` smallint(6) DEFAULT NULL,
    `age_month` smallint(6) DEFAULT NULL,
    `age_year` smallint(6) DEFAULT NULL,
    `birth_date` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `birth_day` tinyint(3) unsigned DEFAULT '0',
    `birth_month` tinyint(3) unsigned DEFAULT '0',
    `birth_year` smallint(5) unsigned DEFAULT '0',
    `birth_date_flag` tinyint(4) unsigned DEFAULT '0',
    `birth_location` int(10) unsigned DEFAULT NULL,
    `birth_location_flag` tinyint(3) unsigned DEFAULT NULL,
    `death` char(1) COLLATE utf8_bin DEFAULT NULL,
    `lifeless_reported` varchar(3) COLLATE utf8_bin DEFAULT NULL,
    `lifeless_reported_flag` varchar(5) COLLATE utf8_bin DEFAULT NULL,
    `death_date` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `death_day` tinyint(3) unsigned DEFAULT '0',
    `death_month` tinyint(3) unsigned DEFAULT '0',
    `death_year` smallint(5) unsigned DEFAULT '0',
    `death_date_flag` tinyint(4) unsigned DEFAULT '0',
    `death_location` int(10) unsigned DEFAULT NULL,
    `death_location_flag` tinyint(3) unsigned DEFAULT NULL,
    `mar_date` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `mar_day` tinyint(3) unsigned DEFAULT '0',
    `mar_month` tinyint(3) unsigned DEFAULT '0',
    `mar_year` smallint(5) unsigned DEFAULT '0',
    `mar_date_flag` tinyint(4) unsigned DEFAULT '0',
    `mar_location` int(10) unsigned DEFAULT NULL,
    `mar_location_flag` tinyint(3) unsigned DEFAULT NULL,
    `divorce_text` varchar(100) COLLATE utf8_bin DEFAULT NULL,
    `divorce_date` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `divorce_day` tinyint(3) unsigned DEFAULT NULL,
    `divorce_month` tinyint(3) unsigned DEFAULT NULL,
    `divorce_year` smallint(5) unsigned DEFAULT NULL,
    `divorce_date_flag` tinyint(4) DEFAULT NULL,
    `divorce_location` int(10) unsigned DEFAULT NULL,
    `divorce_location_flag` tinyint(3) DEFAULT NULL,
    `birth_day_min` smallint(5) unsigned DEFAULT '0',
    `birth_month_min` smallint(5) unsigned DEFAULT '0',
    `birth_year_min` smallint(5) unsigned DEFAULT '0',
    `birth_day_max` smallint(5) unsigned DEFAULT '0',
    `birth_month_max` smallint(5) unsigned DEFAULT '0',
    `birth_year_max` smallint(5) unsigned DEFAULT '0',
    `birth_date_min` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `birth_date_max` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `birth_min_days` int(10) unsigned DEFAULT '0',
    `birth_max_days` int(10) unsigned DEFAULT '0',
    `mar_day_min` smallint(5) unsigned DEFAULT '0',
    `mar_month_min` smallint(5) unsigned DEFAULT '0',
    `mar_year_min` smallint(5) unsigned DEFAULT '0',
    `mar_day_max` smallint(5) unsigned DEFAULT '0',
    `mar_month_max` smallint(5) unsigned DEFAULT '0',
    `mar_year_max` smallint(5) unsigned DEFAULT '0',
    `mar_date_min` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `mar_date_max` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `mar_min_days` int(10) unsigned DEFAULT '0',
    `mar_max_days` int(10) unsigned DEFAULT '0',
    `divorce_day_min` smallint(5) unsigned DEFAULT '0',
    `divorce_month_min` smallint(5) unsigned DEFAULT '0',
    `divorce_year_min` smallint(5) unsigned DEFAULT '0',
    `divorce_day_max` smallint(5) unsigned DEFAULT '0',
    `divorce_month_max` smallint(5) unsigned DEFAULT '0',
    `divorce_year_max` smallint(5) unsigned DEFAULT '0',
    `divorce_date_min` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `divorce_date_max` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `divorce_min_days` int(10) unsigned DEFAULT '0',
    `divorce_max_days` int(10) unsigned DEFAULT '0',
    `death_day_min` smallint(5) unsigned DEFAULT '0',
    `death_month_min` smallint(5) unsigned DEFAULT '0',
    `death_year_min` smallint(5) unsigned DEFAULT '0',
    `death_day_max` smallint(5) unsigned DEFAULT '0',
    `death_month_max` smallint(5) unsigned DEFAULT '0',
    `death_year_max` smallint(5) unsigned DEFAULT '0',
    `death_date_min` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `death_date_max` varchar(20) COLLATE utf8_bin DEFAULT NULL,
    `death_min_days` int(10) unsigned DEFAULT '0',
    `death_max_days` int(10) unsigned DEFAULT '0',
    `birth_date_valid` tinyint(1) unsigned DEFAULT '0',
    `mar_date_valid` tinyint(1) unsigned DEFAULT '0',
    `divorce_date_valid` tinyint(1) DEFAULT NULL,
    `death_date_valid` tinyint(1) unsigned DEFAULT '0',
    `valid_complete` tinyint(1) unsigned DEFAULT '0',
    `familyname_no` int(10) unsigned DEFAULT '0',
    `firstname1_no` int(10) unsigned DEFAULT '0',
    `firstname2_no` int(10) unsigned DEFAULT '0',
    `firstname3_no` int(10) unsigned DEFAULT '0',
    `firstname4_no` int(10) unsigned DEFAULT '0',
    PRIMARY KEY (`id_person`),
    KEY `familyname` (`familyname`),
    KEY `firstname` (`firstname`),
    KEY `id_registration` (`id_registration`),
    KEY `role_age_year` (`role`,`age_year`),
    KEY `firstname1` (`firstname1`),
    KEY `firstname2` (`firstname2`),
    KEY `firstname3` (`firstname3`),
    KEY `firstname4` (`firstname4`),
    KEY `id_source` (`id_source`),
    KEY `registration_maintype` (`registration_maintype`),
    KEY `registration_type` (`registration_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
